source:      .
destination: target

# Inherited from default config:

plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output: true
  lessons:
    output: true




defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

  -
    scope:
      path: "lessons"
    values:
      layout: "lesson"


  -
    scope:
      path: "posts"
    values:
      layout: "default"